config/routes.rb
Pielab::Application.routes.draw do
  root :to => 'static_pages#home'
  
  match '/about', :to => "static_pages#about"
  match '/signup', :to => "users#new"
  match '/signin', :to => "sessions#new"
  match '/signout', :to => "sessions#destroy", :via => :delete
  match '/blog', :to => "posts#index"

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :posts
  resources :images, :only => [:new, :create, :destroy, :index]

end

app/models/image.rb
class Image < ActiveRecord::Base
  attr_accessible :post_id, :image_file
  belongs_to :post

  has_attached_file :image_file, { :styles => { :large => "700x700>",
                                                :medium => "500x500>",
                                                :small => "300x300>",
                                                :thumb => "100x100>" },
                                   :url => "/system/:class/:attachment/:filename_:style",
                                   :path => ":rails_root/public/system/:class/:attachment/:filename_:style" }

  validates_attachment :image_file,
      :presence => :true,
      :content_type => { :content_type => ["image/jpg", "image/png", "image/gif"] },
      :size =>  { :in => 0..5120.kilobytes }
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_filter :signed_in_user, only: [:create, :new, :index]
  before_filter :admin_user, only: [:destroy]

  def create
      @image = Image.new(params[:image])
      if @image.save
          flash[:success] = render_to_string(:partial => 'saved_flash').html_safe
          redirect_back_or root_path 
      else
          flash[:error] = "Image could not be uploaded."
          redirect_back_or root_path
      end
  end

  def destroy
      Image.find(params[:id]).destroy
      flash[:success] = "Image deleted."
      redirect_back_or images_path
  end

  def new
      store_location
      @image = Image.new
  end

  def index
      store_location
      @images = Image.paginate(page: params[:page])
  end

  private
        
    def admin_user
        redirect_to(root_path) unless admin?
    end

    def store_image_url(url)
        session[:image_url] = url
    end

end

app/views/images/_image.html.erb
<li class="span2">
<a href=<%= image.image_file.url %> class="thumbnail">
       <%= image_tag image.image_file.url(:small) %> 
   </a>
   <p>
       <%= link_to image.image_file_file_name, image.image_file.url %>
       <% if current_user.admin? %>
           | <%= link_to "delete", image, method: :delete,
                                            data: { confirm: "Are you sure?" } %>
       <% end %>
   </p>
</li>

app/views/images/_saved_flash.html.erb
<%= "Image saved to: #{link_to(@image.image_file.url, @image.image_file.url)}".html_safe %>

app/views/images/index.html.erb
<% provide(:title, 'All images') %>
<h1>All images</h1>

<%= will_paginate %>

  <ul class="thumbnails">
    <%= render @images %>
  </ul>

  <%= link_to "+ Add image", new_image_path %>

<%= will_paginate %>

app/views/images/new.html.erb
<aside class="span4">
    <section>
    <%= render 'shared/image_form' %>
    </section>
</aside>