config/routes.rb
Pielab::Application.routes.draw do
  root :to => 'static_pages#home'
  
  match '/about', :to => "static_pages#about"
  match '/signup', :to => "users#new"
  match '/signin', :to => "sessions#new"
  match '/signout', :to => "sessions#destroy", :via => :delete
  match '/blog', :to => "posts#index"

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :posts
  resources :images, :only => [:new, :create, :destroy, :index]

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Copyright PieLab Research, 2013
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <%= link_to "PieLab", root_path, :id => "logo" %>
                <nav>
                    <ul class="nav pull-right">
                        <li><%= link_to "Blog", posts_path %></li>
                        <li><%= link_to "About", about_path %></li>
                        <% if admin? %>
                            <li><%= link_to "Users", users_path %></li>
                        <% end %>
                        <% if signed_in? %>
                            <li><%= link_to "New Post", new_post_path %></li>
                            <li><%= link_to "Images", images_path %></li>
                            <li id="fat-menu" class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    Account <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">
                                    <li><%= link_to "Posts", current_user %></li>
                                    <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                                    <li class="divider"></li>
                                    <li>
                                        <%= link_to "Sign out", signout_path, method: "delete" %>
                                    </li>
                                </ul>
                            </li>
                        <% else %>
                            <li><%= link_to "Sign in", signin_path %></li>
                        <% end %>
                    </ul>
                </nav>
            </div>
        </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
      <title><%= full_title(yield(:title)) %></title>
      <%= stylesheet_link_tag    "application", :media => "all" %>
      <%= javascript_include_tag "application" %>
      <%= csrf_meta_tags %>
      <%= render 'layouts/shim' %>
    </head>
    <body>
        <%= render 'layouts/header' %>
        <div class="container">
            <div class="span12">
            <% flash.each do |key, value| %>
                <%= content_tag(:div, value, class: "alert alert-#{key}") %>
            <% end %>
            </div>
            <%= yield %>
            <%= debug(params) if Rails.env.development? %>
        </div>
    </body>
</html>